services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: odyssey-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - odyssey-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    restart: always
    container_name: odyssey-backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - PROJET_NAME=${PROJECT_NAME}
      - DEBUG=${DEBUG}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - odyssey-network
      - npm_network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    restart: always
    container_name: odyssey-frontend
    depends_on:
      - backend
    networks:
      - odyssey-network
      - npm_network

volumes:
  postgres_data:
  uploads_data:


networks:
  odyssey-network:
    driver: bridge
  npm_network:
    external:
      name: npm-prod_default
